### ISSUE TITLE
ScandiPWA displaying blank page in the frontend.

### ISSUE THREAD

**Issue by shivampmc** [scandipwa/scandipwa#2511]
I have installed ScandiPWA using composer in existing Magento 2.4.1 instance and changed the theme to my new ScandiPWA theme from the backend. Now when I visit the frontend it displays an empty page and in the console it shows chunks not found
![image](https://user-images.githubusercontent.com/77787433/115219993-acce5f80-a125-11eb-954f-5243bde12d18.png)

Steps I followed to install ScandiPWA:
1. Upgraded Magento to 2.4.1
2. Installed ScandiPWA using yarn create scandipwa-app appname in <magento_root>/src/localmodules
3. Ran BUILD_MODE=magento yarn build in the scandipwa app directory.
4. From Magento root directory ran composer command to link composer config repo.theme path src/localmodules/<my-app-name> and then ran composer require scandipwa/<my-app-name> 
5. Configured persisted query using bin/magento setup:config:set --pq-host=127.0.0.1 --pq-port=6379 --pq-database=5 --pq-scheme="tcp"
6. Ran the following commands bin/magento setup:upgrade  bin/magento cache:disable full_page and enabled ScandiPWA theme in the backend and then ran bin/magento cache:flush
7. Additionally tried to run bin/magento setup:upgrade, di:compile, deploy:static-content afterwards just in case

**Comment by rajnibalayadavtest** [comment]
Hi
I also having the same issue. @shivampmc  have you got any solution for this?

**Comment by shivampmc** [comment]
Make sure your Magento is being served from the pub directory and not the root directory.

**Comment by rajnibalayadavtest** [comment]
Yes its in pub directory, as per magneto 2.4.2 i am using and its not work without pub.

**Comment by shivampmc** [comment]
Configure Redis and Varnish properly.

I fixed it by configuring Redis properly and serving Magento from the pub.

**Comment by rajnibalayadavtest** [comment]
Without varnish it will not work right ?
I feel varnish is optional so I haven't installed it.

**Comment by shivampmc** [comment]
Not sure if Varnish is optional or not but I have it installed just in case.

**Comment by Zahidcs** [comment]
Still facing frontend is blank magento 2.4.4 and scandipwa 6+
