### ISSUE TITLE
Magento 2.4.3 upgrade: Support for Page Builder

### ISSUE THREAD

**Issue by tatiana-scandi** [scandipwa/scandipwa#3260]
**Description**:
Magento 2.4.3 upgrade introduced new Page Builder. Looks like it's not 100% compatible with ScandiPWA, because after saving (even without changes) pages have broken UI with raw html markup (see screenshots).

**Expected behavior**:
Pages should be editable via Page Builder.

**Screenshots, Video, Logs**
Original page:
https://scandipwapmrev.indvp.com/default/hakuna-matata
![image](https://user-images.githubusercontent.com/79456428/131876972-a98bb275-7151-4750-8e50-9494f33e93fe.png)

Duplicated page:
https://scandipwapmrev.indvp.com/default/hakuna-matata-2
![image](https://user-images.githubusercontent.com/79456428/131877094-155f2f28-b316-4f58-890f-b1f4e1a492a5.png)

**To Reproduce**:
1. Login to Magento admin (https://scandipwapmrev.indvp.com/admin)
2. Navigate to Content -> Pages
3. Open 'Hakuna Matata' page and create it's duplicate (Save -> Save & Duplicate)
4. Open created page on the website
5. Note that text elements are displayed as HTML markup

**Versions**:
- ScandiPWA: 5.0.3

**Comment by tatiana-scandi** [comment]
Will probably be fixed by https://marketplace.scandipwa.com/magento-2-page-builder.html

**Comment by roynguyen-scandiweb** [comment]
Fixed at [this commit](https://github.com/roynguyen-scandiweb/pagebuilder-ext/commit/243d24489d1f1fd2024aa4ab6aa3138067c6ed24)
@tatiana-scandi Please help to test it again. Thanks much!

**Comment by roynguyen-scandiweb** [comment]
@tatiana-scandi hello, I alread push the fix. Please check it here https://github.com/roynguyen-scandiweb/pagebuilder-ext

**Comment by tatiana-scandi** [comment]
@roynguyen-scandiweb has the extension been added to list of enabled modules for http://scandipwapmrev.indvp.com/? Page translations will not be working until the extension is enabled on this server (in `package.json` file). Now I still see broken page here: https://scandipwapmrev.indvp.com/default/hakuna-matata-2
I suppose this change should be included into the release, but you'd rather ask Carina how to do it correctly (and how exactly the `page-builder` extension is to be used).

**Comment by roynguyen-scandiweb** [comment]
hi @tatiana-scandi , I didn't add the module to http://scandipwapmrev.indvp.com/ . Liana told that there are some guy will do the job

**Comment by sebastianburzynski** [comment]
Are there any updates on this one ? The fix is for magento 2.4.3 but which version of ScandiPWA is this https://github.com/roynguyen-scandiweb/pagebuilder-ext is compatibile with ? @roynguyen-scandiweb
