### ISSUE TITLE
Install Requirements

### ISSUE THREAD

**Issue by andrewa17github** [scandipwa/scandipwa#5507]
Installing ScandiPWA on clean minimal CentOS 9 has install errors.

NPM 8.19.4
Node 16.20.2
Python 3.9.18
Composer 2.6.6

`npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Command failed: /usr/bin/python3 -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1`

With a lot of deprecated warnings, is it correct latest Scandipwa 6.2.3 is built on older versions such as python2.

**Comment by Andrii-Antoniuk** [comment]
Yes, ScandiPWA forces to use node 14
So unfortunately, the reqs are not `>= node 14` but `= node 14`

**Comment by devondragon** [comment]
As Node 14 was End of Lifed almost a year ago, back in April of 2023, what is the roadmap for ScandiPWA to work with modern supported versions of Node (20+)?

**Comment by Andrii-Antoniuk** [comment]
@andrewa17github @devondragon 
I got an update about this - it is on the roadmap :) 
Unfortunately, there is no estimate yet.
There is a long list of breaking changes with updating the node version, so the current state is "work in progress" 😉

**Comment by Andrii-Antoniuk** [comment]
@andrewa17github @devondragon we have released new version with LTS node support !

**Comment by andrewa17github** [comment]
These node and npm apps are really not very stable, tried the new version with following and errors, will look in to it but have our own headless/pwa graphql in to Magento which is eminently more stable as it's not a runtime app, we we hoping to use Scandi for other sites but still cannot get a install going on clean CentOS Stream 9, don't worry all the other PWA are the same, Venia, Vue, GraphCommerce, our conclusion is there's an underlying technology issue to stability with these npm apps as we run stores with 100,000s products and more, will try and work with Scandi but it's 2months since first posted the issue.

`Starting the development server...



  build [==========          ] 51%/var/www/web/.../node_modules/react-scripts/scripts/start.js:19

  throw err;

  ^



RpcIpcMessagePortClosedError: Process 2201017 exited [SIGKILL].

    at /var/www/web/.../node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:19:23

    at Generator.next (<anonymous>)

    at /var/www/web/.../node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:8:71

    at new Promise (<anonymous>)

    at __awaiter (/var/www/web/.../node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:4:12)

    at ChildProcess.handleExit (/var/www/web/.../node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:18:42)

    at ChildProcess.emit (node:events:517:28)

    at ChildProcess.emit (node:domain:489:12)

    at ChildProcess._handle.onexit (node:internal/child_process:292:12) {

  code: null,

  signal: 'SIGKILL'

}



Node.js v18.19.1
`

**Comment by andrewa17github** [comment]
When it starts it's opening a browser at localhost:3000, if there is an anomaly which happened on Node:18 it failed, this caused a subsequent launches to fail, a complete reset with Node:20 started correctly.
